version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:124709293187:task-definition/currencyexchange:3"
        LoadBalancerInfo:
          ContainerName: "containercurrencyexchange"
          ContainerPort: "8000"
        PlatformVersion: "LATEST"