version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
    - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
    - IMAGE_URI=${REPOSITORY_URI}:${TAG}
  build:
    commands:
    - echo Build started on `date`
    - mvn clean package
    - docker build -t currencyexchange .
    - docker build currencyexchange:latest --tag 124709293187.dkr.ecr.us-east-1.amazonaws.com/currencyexchange:latest .
  post_build:
    commands:
    - printenv
    - echo Build completed on `date`
    - echo $(docker images)
    - echo Pushing docker image
    - docker push 124709293187.dkr.ecr.us-east-1.amazonaws.com/currencyexchange:latest
    - echo push completed
    - printf '[{"name":"%s","imageUri":"124709293187.dkr.ecr.us-east-1.amazonaws.com/currencyexchange:latest"}]' $CONTAINER_NAME > imagedefinitions.json
artifacts:
  files:
  - imagedefinitions.json